es_host: elasticsearch
es_port: ${ELASTICSEARCH_PORT}
es_username: ${ELASTICSEARCH_USER}
es_password: ${ELASTICSEARCH_PASSWORD}

writeback_index: elastalert_status

rules_folder: /opt/elastalert/rules
run_every:
  seconds: 10

buffer_time:
  minutes: 15

alert_time_limit:
  days: 2

# es_timeout: 120

# Email settings

smtp_host: ${SMTP_HOST}
smtp_port: ${SMTP_PORT}
smtp_ssl: false
from_addr: ${FROM_ADDR}
smtp_auth_file: /opt/elastalert/smtp_auth.yml
