input {
  http {
    port => 5044  
    codec => "json"
  }
}

filter {
  json {
    source => "body"
  }
}


output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "heartbeat-logs" 
    user => "logstash_internal"
    password => "${LOGSTASH_INTERNAL_PASSWORD}" # Configure this in your environment
  }

  stdout { codec => rubydebug }  # Debug output in de Logstash console
}
