input {
  http {
    port => 5044  
    codec => plain  
  }
}

filter {
  xml {
    source => "message" 
    store_xml => true
    target => "parsed_xml" 
    remove_field => ["headers", "host"]  
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "heartbeat-logs" 
    user => "logstash_internal"
    ## password => "${LOGSTASH_INTERNAL_PASSWORD}" # Configureer in je omgeving
  }

  stdout { codec => rubydebug }  # Debug output in Logstash console
}
