input {
  http {
    port => 5044  # Moet overeenkomen met de URL in Python (LOGSTASH_URL)
    codec => "json"
  }
}

filter {
  json {
    source => "message"  # Zorg ervoor dat JSON correct wordt verwerkt
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "heartbeat-logs"
    user => "logstash_internal"
    password => "${LOGSTASH_INTERNAL_PASSWORD}"
  }

  stdout { codec => rubydebug }  # Debug output in de Logstash console
}
